source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/ZYComponent/ZYSpecs.git'

use_frameworks!

target 'ZYSpecialKit_Example' do
  pod 'ZYSpecialKit', :path => '../'

  target 'ZYSpecialKit_Tests' do
    inherit! :search_paths

    
  end
end
